stages:
    - "infrastructure"
    - "build"
    - "deploy-to-dev"
    - "deploy-to-prod"

infrastructure:
    stage: infrastructure
    image: zenika/terraform-aws-cli:release-6.0_terraform-1.3.7_awscli-1.27.60
    before_script:
        - echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    script:
        - cd terraform
        - terraform init
        - terraform apply --auto-approve
        - terraform output kubeconfigdev > configdev
        - terraform output kubeconfigprod > configprod
        - sed '1d;$d' configdev| cp /dev/stdin /builds/Janortop5/capstone-microservices-demo-watchn/terraform/configdev
        - sed '1d;$d' configprod| cp /dev/stdin /builds/Janortop5/capstone-microservices-demo-watchn/terraform/configprod
    artifacts:
      paths:
      - /builds/Janortop5/capstone-microservices-demo-watchn/terraform/configdev
      - /builds/Janortop5/capstone-microservices-demo-watchn/terraform/configprod
      expire_in: 1 week

build_images:
    stage: build
    image: docker:23.0.1-cli
    services:
        - docker:23.0.1-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    script:
        - cd src/ui
        - docker build -t janortop5/watchn-ui:latest --build-arg JAR_PATH=target/ui-0.0.1-SNAPSHOT.jar .
        - cd /builds/Janortop5/capstone-microservices-demo-watchn/src/catalog
        - docker build -t janortop5/watchn-catalog:latest .
        - cd /builds/Janortop5/capstone-microservices-demo-watchn/src/cart
        - docker build -t janortop5/watchn-carts:latest --build-arg JAR_PATH=target/carts-0.0.1-SNAPSHOT.jar .
        - cd /builds/Janortop5/capstone-microservices-demo-watchn/src/orders
        - docker build -t janortop5/watchn-orders:latest --build-arg JAR_PATH=target/orders-0.0.1-SNAPSHOT.jar .
        - cd /builds/Janortop5/capstone-microservices-demo-watchn/src/checkout
        - docker build -t janortop5/watchn-checkout:latest .
        - cd /builds/Janortop5/capstone-microservices-demo-watchn/src/assets
        - docker build -t janortop5/watchn-assets:latest .
        - cd /builds/Janortop5/capstone-microservices-demo-watchn/images/activemq
        - docker build -t janortop5/watchn-activemq:latest .
        - docker push janortop5/watchn-ui:latest
        - docker push janortop5/watchn-catalog:latest
        - docker push janortop5/watchn-carts:latest
        - docker push janortop5/watchn-orders:latest
        - docker push janortop5/watchn-checkout:latest
        - docker push janortop5/watchn-assets:latest
        - docker push janortop5/watchn-activemq:latest

deploy_to_dev:
    stage: deploy-to-dev
    image:
        name: dtzar/helm-kubectl:latest
        entrypoint: ['']
    before_script:
        - curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.9/aws-iam-authenticator_0.5.9_linux_amd64
        - chmod +x ./aws-iam-authenticator
        - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
        - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
        - aws-iam-authenticator help
    script:
        - kubectl
        - helm
        - wget https://github.com/helmfile/helmfile/releases/download/v0.154.0/helmfile_0.154.0_linux_amd64.tar.gz
        - tar xvzf helmfile_0.154.0_linux_amd64.tar.gz
        - cp helmfile /usr/sbin
        - helmfile
        - helm plugin install https://github.com/databus23/helm-diff
        - export KUBECONFIG=/builds/Janortop5/capstone-microservices-demo-watchn/terraform/configdev
        - kubectl get nodes

deploy_to_production:
    stage: deploy-to-prod
    image:
        name: dtzar/helm-kubectl:latest
        entrypoint: ['']
    before_script:
        - curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.9/aws-iam-authenticator_0.5.9_linux_amd64
        - chmod +x ./aws-iam-authenticator
        - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
        - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
        - aws-iam-authenticator help
    script:
        - kubectl
        - helm
        - wget https://github.com/helmfile/helmfile/releases/download/v0.154.0/helmfile_0.154.0_linux_amd64.tar.gz
        - tar xvzf helmfile_0.154.0_linux_amd64.tar.gz
        - cp helmfile /usr/sbin
        - helmfile
        - helm plugin install https://github.com/databus23/helm-diff
        - export KUBECONFIG=/builds/Janortop5/capstone-microservices-demo-watchn/terraform/configprod
        - kubectl get nodes


