stages:
    - "infrastructure"
    - "build"
    - "deploy-to-dev"
    - "deploy-to-prod"

infrastructure:
    stage: infrastructure
    image: zenika/terraform-aws-cli:release-6.0_terraform-1.3.7_awscli-1.27.60
    before_script:
        - echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    script:
        - cd terraform
        - terraform init
        - terraform apply --auto-approve
        - terraform output kubeconfigdev > configdev
        - terraform output kubeconfigprod > configprod
        - sed '1d;$d' configdev| cp /dev/stdin configdev
        - sed '1d;$d' configprod| cp /dev/stdin configprod
    artifacts:
      paths:
      - /builds/Janortop5/capstone-microservices-demo-watchn/terraform/configpdev
      - /builds/Janortop5/capstone-microservices-demo-watchn/terraform/configprod
      expire_in: 1 week

did_it_workk:
    stage: build
    image: ubuntu:22.10
    script:
        - cat /builds/Janortop5/capstone-microservices-demo-watchn/config

deploy_to_dev:
    stage: deploy-to-dev
    image:
        name: dtzar/helm-kubectl:latest
        entrypoint: ['']
    script:
        - kubectl
        - helm
        - wget https://github.com/helmfile/helmfile/releases/download/v0.154.0/helmfile_0.154.0_linux_amd64.tar.gz
        - tar xvzf helmfile_0.154.0_linux_amd64.tar.gz
        - cp helmfile /usr/sbin
        - helmfile
        - helm plugin install https://github.com/databus23/helm-diff

    # script:
    #     - export KUBECONFIG=/builds/Janortop5/capstone-microservices-demo-watchn/config
    #     - kubectl get nodes
