name: Build and Test Docker Image

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false  # Set to true if you want to push the image to a registry
          tags: my-docker-image:latest

      - name: Run tests using Docker
        run: |
          docker run --rm my-docker-image:latest /bin/bash -c "
          apk add --no-cache bash &&
          cd src/e2e &&
          chmod +x ./scripts/run-docker.sh &&
          ./scripts/run-docker.sh 'http://endpoint:8080'"
