name: Run tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      my-service:
        image: my-service-image
        ports:
          - 8080:8080
        options: >-
          --health-cmd "curl -f http://localhost:8080 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Run tests using Docker
        run: |
          cd src/e2e &&
          chmod +x ./scripts/run-docker.sh &&
          ./scripts/run-docker.sh 'http://localhost:8080'

      - name: Debug Network
        run: |
          nslookup localhost
          ping -c 4 localhost
          curl -v http://localhost:8080
